# -*- coding: utf-8 -*-
"""iris

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1daYNSLEbjjhn_YCo-jpgseE1CHOdd4cy
"""



import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
dataset = pd.read_csv('Iris.csv')

# Visualize the dataset using pairplot
sns.pairplot(dataset, hue='Species')

# Add a title to the plot
plt.title("Iris Dataset - Pairplot")

# Display the plot
plt.show()

# Separate the features and target variable
X = dataset.drop('Species', axis=1)
y = dataset['Species']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocess the data - Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train the model - Support Vector Machine (SVM)
model = SVC()
model.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(dataset.head(150))

